language: node_js
node_js:
  - "4.1"

cache:
  directories:
    - node_modules

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g gulp jspm
  - jspm install

script:
  - gulp
