language: node_js
node_js:
  - "4.1"

cache:
  directories:
    - node_modules
    - jspm_packages

install:
  - npm install
  - node_modules/.bin/jspm install

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - node_modules/.bin/gulp